version: '3'
services:
  rwsols:
    build: .
    image: rwsols
    restart: unless-stopped
    ports:
      - "2000:443"
    environment:
      WOL_PASSWORD_HASH: 37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f
      WOL_MAX_PING: 5
      WOL_SLEEP_TIME: 10
      WOL_COMPUTER_NAMES: ordi1,ordi2
      WOL_COMPUTER_MACS: 00:00:00:11:11:11,00:00:00:22:22:22
      WOL_COMPUTER_LOCAL_IPS: 192.168.1.1,192.168.1.2
      WOL_HTTPS_PORT: 2000
      WOL_HTTP_PORT: 2001
    network_mode: host
    volumes:
      - ./ssl/:/etc/apache2/ssl
